# -*- coding: utf-8 -*-
"""hhapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14DuqdPERX7PmTZY83bHYlRO5l_i2pq6Y
"""
'''
#!pip install flask-ngrok

#from google.colab import files
#uploaded = files.upload()

import zipfile
from zipfile import ZipFile

file_name = '/content/templates.zip'

with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Extracted Successfully')

!mkdir static

cd static

!mkdir images

cd ..
'''
import tensorflow as tf
import os

import flask
from flask import Flask, render_template, request
from flask_ngrok import run_with_ngrok

from keras.preprocessing.image import load_img, img_to_array
from keras.applications.vgg16 import VGG16, preprocess_input, decode_predictions

app = Flask(__name__)
run_with_ngrok(app)

image_folder = os.path.join('static', 'images')
app.config["UPLOAD_FOLDER"] = image_folder

model = VGG16()

@app.route('/', methods=['GET'])
def home():
  return render_template('index.html')

@app.route('/', methods=['POST'])
def predict():
  imagefile = request.files['imagefile']
  image_path = './static/images/' + imagefile.filename
  imagefile.save(image_path)

  image = load_img(image_path, target_size=(224, 224))
  image = img_to_array(image)
  image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
  image = preprocess_input(image)
  yhat = model.predict(image)
  label = decode_predictions(yhat)
  label = label[0][0]

  classification = '%s (%.2f%%)'%(label[1], label[2]*100)

  pic = os.path.join(app.config['UPLOAD_FOLDER'], imagefile.filename)

  return render_template('index.html', user_image=pic, prediction_text=classification)

app.run()

